spring:
    application:
        name: CONFIG-SERVER
    cloud:
        config:
            server: 
                git: 
                    uri: https://github.com/deshapriya199/practise-cloud-config-server/

server:
   port: 9193 